### ISSUE TITLE
Support loading credentials

### ISSUE THREAD

**Issue by negz** [crossplane/function-sdk-go#139]
### What problem are you facing?

Crossplane v1.16 added support for passing credentials to secrets - https://github.com/crossplane/crossplane/pull/5543.

### How could Crossplane help solve your problem?

This SDK should update its protobufs (at least) and potentially add helper utils to get those credentials.

**Comment by TerjeLafton** [comment]
@negz 
Composition functions are really amazing, and I find myself using this SDK every time I have to write a composition.

As this SDK is very tightly coupled with the rest of Crossplane, would it be a good idea to version it like the rest too?
So when this gets updated to support the new fields from 1.16, that should be the 1.16 release of this SDK.

It should probably also be maintained with Crossplane too. Upgrading to Crossplane 1.16 now and then realize the SDK does not support it is unfortunate.

**Comment by negz** [comment]
@TerjeLafton Sure, it's a good idea. Unfortunately this is a large project with few maintainers, and I haven't had time to cut a release yet.

If you're interested in becoming a maintainer on this repo to help with this kind of things, it would be appreciated.

**Comment by negz** [comment]
> As this SDK is very tightly coupled with the rest of Crossplane, would it be a good idea to version it like the rest too? So when this gets updated to support the new fields from 1.16, that should be the 1.16 release of this SDK.

I don't think it's that tightly coupled, actually. It needs a new release when new features are added to functions but I don't think every new Crossplane release will warrant a new SDK release.
