### ISSUE TITLE
Add a way to log errors within the function

### ISSUE THREAD

**Issue by chaitanyakolluru** [crossplane/function-sdk-go#143]
### What problem are you facing?

 Logger for functions defined [here](https://github.com/crossplane/function-sdk-go/blob/main/logging/logging.go#L34) is setup to proxy logger defined in crossplane-runtime [here](github.com/crossplane/crossplane-runtime/pkg/logging), which only allows logging `Info` and `Debug` level logs as function logs. As `RunFunction` is only expected to append errors as `Results` to `RunFunctionResponse` and that it never returns an error even when we add a fatal result to the `RunFunctionResponse`, 
outside of looking at XRs status we don't have a means to log those errors on the function.

### How could Crossplane help solve your problem?

The solution suggested would involve setting up a `FnLogger` interface with `Error()` added and an implementation to invoke logger's Error() method to log errors. 
Please find the proposed changes [here](https://github.com/crossplane/function-sdk-go/pull/144/files).

**Comment by negz** [comment]
What's the benefit of a dedicated `Error` method on the logger? Why not log errors at `Info` or `Debug` as appropriate, e.g.:

```go
log.Info("Something went wrong", "error", err")
```

**Comment by chaitanyakolluru** [comment]
i) Better and clearer syntax when logging an error.  As an example:

Assuming xrMetadata is keys and values holding xr metadata information,
with Info:
```
        ...
  	log.Info(msg, xrMetadata...)
	response.Fatal(rsp, errors.New(msg))

	return rsp, nil
``` 

where xrMetadata needs to now include ["errors", errors]

vs with Error:
```
        ...
	log.Error(incomingErr, msg, xrMetadata...)
	response.Fatal(rsp, errors.New(msg))

	return rsp, nil
```
 
where xrMetadata can simply be xr metadata.

ii) Error spits out stacktrace by default without any other changes to the way logger is setup:

```
{"level":"error","ts":"2024-06-03T21:12:26Z","logger":"fn-name","msg":"failed message", KeysAndValues..., "stacktrace":"stacktrace\n"}
{"level":"info","ts":"2024-06-03T21:12:26Z","logger":"fn-name","msg":"failed message", KeysAndValues...}
```

iii) Also, seeing that, per function development convention, functions will never return an error but `rsp, nil` with error details added as a Result within rsp,  I think it makes sense for us to have a dedicated Error method on fn's logger (not Crossplane-runtime's) to indicate that developers can log error states outside of setting Result on `RunFunctionResponse`.

It is workable with Info(), but think it would be cleaner with a dedicated Error method on Logger interface.

**Comment by chaitanyakolluru** [comment]
Emitting logs using `Info` method does seem favorable seeing that we don't need the stacktrace and that we can include error metadata within `keysAndValues`. Closing this issue.
