### ISSUE TITLE
How should we handle logging and errors?

### ISSUE THREAD

**Issue by negz** [crossplane/function-sdk-go#22]
### What problem are you facing?

https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v1.13.0/pkg/errors
https://pkg.go.dev/github.com/crossplane/crossplane-runtime@v1.13.0/pkg/logging

You can think of crossplane-runtime as a "Go SDK" of sorts for parts of Crossplane - i.e. core and providers. We have our own error and logging libraries there. Should Functions use those libraries? Use copies/aliases from this SDK? Use the stdlib or something else?

### How could Crossplane help solve your problem?

We should figure out what we want to do here. I can see a case for sticking closer to the stdlib here given that now Go can do the core things our libraries were originally created to do for us (i.e. wrap errors, and emit structured logs).

Some thoughts:
* Admittedly I personally prefer the "UX" for the crossplane-runtime libraries to the stdlib alternatives.
* If stdlib is good enough for Functions, is it good enough for Crossplane now too?

**Comment by phisco** [comment]
Given that we are already importing `github.com/crossplane/crossplane-runtime` to access things such as composed/composite resources, there is no real value in switching to the stdlib.

**Comment by negz** [comment]
@phisco WDYT about adding logging/errors packages to the SDK that just mirror/call through to c/crossplane-runtime? That at lease keeps Functions slightly decoupled and gives us the option to change how the SDK is implemented in future.

**Comment by phisco** [comment]
That would at least make it easier to discover. Sounds good to me!
